In [1]:
import torch
import numpy as np
from encode import encode_board, decode_board
from game import Connect4
from mcts import MCTS
from network import ConnectNet

In [2]:
from self_play_learning import SelfPlay

In [3]:
game = Connect4()

In [4]:
b = game.init_state

In [5]:
game.check_winner(game.init_state)

0

In [6]:
p=1

In [7]:
b, p = game.step(2, b, p)

In [8]:
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [9]:
game.check_winner(b)

0

In [10]:
net = ConnectNet()

In [11]:
net(torch.tensor(encode_board(b)).float())

(tensor([[0.1270, 0.1692, 0.1468, 0.1266, 0.1714, 0.1255, 0.1335]],
        grad_fn=<ExpBackward>), tensor([[-0.1720]], grad_fn=<TanhBackward>))

In [12]:
decode_board(encode_board(b, p))

(array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]]), -1)

In [13]:
args = {"n_sim":10, "exploration_constant":1.,"scale":1., "tempThreshold":15}
mcts = MCTS(game, net, args)

In [14]:
mcts.search(b)

0.17202228

In [15]:
mcts.run_sims(b)

[0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1]

In [16]:
env = Connect4()

In [21]:
coach = SelfPlay(game, net, args)

In [23]:
train_examples = coach.run_episode()

In [25]:
train_examples[-1]

(array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0., -1.,  0., -1.,  1.,  1.,  0.],
        [ 0., -1.,  0.,  1., -1.,  1.,  0.],
        [ 0.,  1.,  0., -1.,  1., -1., -1.]]), [0, 0, 0, 0, 0, 1, 0], 1)

In [26]:
game.check_winner(train_examples[-1][0])

0

In [40]:
list(np.random.randint(0,10,4))

[5, 2, 9, 9]