In [1]:
import torch
import numpy as np
from encode import encode_board, decode_board
from game import Connect4
from mcts import MCTS
from network import ConnectNet

In [2]:
from self_play_learning import SelfPlay

In [3]:
game = Connect4()

In [4]:
b = game.init_state

In [5]:
game.check_winner(game.init_state)

0

In [6]:
p=1

In [7]:
b, p = game.step(2, b, p)

In [8]:
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [9]:
game.check_winner(b)

0

In [10]:
net = ConnectNet()

In [11]:
net(torch.tensor(encode_board(b)).float())

(tensor([[0.1270, 0.1692, 0.1468, 0.1266, 0.1714, 0.1255, 0.1335]],
        grad_fn=<ExpBackward>), tensor([[-0.1720]], grad_fn=<TanhBackward>))

In [12]:
decode_board(encode_board(b, p))

(array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]]), -1)

In [13]:
args = {"n_sim":10, "exploration_constant":1.,"scale":1., "tempThreshold":15}
mcts = MCTS(game, net, args)

In [14]:
mcts.search(b)

0.17202228

In [15]:
mcts.run_sims(b)

[0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1]

In [16]:
env = Connect4()

In [21]:
coach = SelfPlay(game, net, args)

In [23]:
train_examples = coach.run_episode()

In [25]:
train_examples[-1]

(array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0., -1.,  0., -1.,  1.,  1.,  0.],
        [ 0., -1.,  0.,  1., -1.,  1.,  0.],
        [ 0.,  1.,  0., -1.,  1., -1., -1.]]), [0, 0, 0, 0, 0, 1, 0], 1)

In [26]:
game.check_winner(train_examples[-1][0])

0

In [40]:
list(np.random.randint(0,10,4))

[5, 2, 9, 9]

In [69]:
l=[(np.random.randn(6,7), list(np.random.randint(0,1,7)), np.random.randn()) for i in range(10)]

In [71]:
l

[(array([[-0.85869366, -1.24892913, -1.36701825, -1.23036267,  1.97699475,
           0.11706677, -0.56508194],
         [-0.35223274,  1.84204285, -0.54460943, -1.11854037,  1.39922637,
          -0.5195588 ,  0.24260098],
         [-0.10748815, -0.09088452, -1.782514  , -0.53173529,  1.03551202,
           1.39265405,  0.23898227],
         [ 0.90463277,  1.17765031, -1.47451022,  0.34496927,  0.24178963,
          -0.733711  , -0.8321649 ],
         [-0.43883238, -0.48499464, -0.84715794,  1.12524994, -0.02790019,
          -1.35898891,  0.61949578],
         [-0.24496008, -0.48122028,  0.29734894, -0.69184777,  0.14716832,
           0.10451271,  0.32779838]]),
  [0, 0, 0, 0, 0, 0, 0],
  -1.2522519080235233),
 (array([[ 0.54373947,  0.38561567,  0.88708363, -0.0295319 ,  0.39011563,
           1.59148095,  0.57291181],
         [-0.86383747,  1.03600174,  1.6585602 , -0.99715054,  0.08043108,
           2.23806585,  0.57556062],
         [ 1.83931457, -0.52618785,  0.2017119 ,  0.3

In [49]:
sum(l, [])

[8,
 8,
 5,
 2,
 0,
 2,
 2,
 9,
 5,
 3,
 9,
 2,
 8,
 8,
 0,
 9,
 7,
 3,
 9,
 4,
 4,
 8,
 8,
 2,
 7,
 6,
 7,
 9,
 7,
 4,
 2,
 8,
 2,
 1,
 9,
 3,
 2,
 9,
 4,
 1]

In [51]:
np.random.shuffle(l)

In [56]:
torch.stack(l)

tensor([[7, 5, 5, 4],
        [6, 7, 0, 2],
        [9, 3, 2, 6],
        [1, 1, 9, 9],
        [9, 5, 1, 0],
        [7, 5, 2, 9],
        [1, 2, 8, 8],
        [4, 2, 6, 0],
        [5, 5, 5, 0],
        [3, 6, 9, 1]])