In [1]:
import torch
import numpy as np
from encode import encode_board, decode_board
from game import Connect4
from mcts import MCTS
from network import ConnectNet

In [2]:
game = Connect4()

In [3]:
b = game.init_state

In [4]:
game.check_winner(game.init_state)

0

In [5]:
p=1

In [6]:
b, p = game.step(3, b, p)

In [7]:
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [8]:
game.check_winner(b)

0

In [11]:
net = ConnectNet()

In [12]:
net(torch.tensor(encode_board(b)).float())

(tensor([[0.1422, 0.1118, 0.1241, 0.2096, 0.1328, 0.0903, 0.1891]],
        grad_fn=<ExpBackward>), tensor([[-0.0192]], grad_fn=<TanhBackward>))

In [13]:
decode_board(encode_board(b, p))

(array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]]), -1)

In [14]:
args = {"n_sim":10, "exploration_constant":1.,"scale":1.}
mcts = MCTS(game, net, args)

In [15]:
mcts.search(b)

0.019194826

In [16]:
mcts.run_sims(b)

[0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.3]

In [22]:
import torch

In [28]:
torch.relu(torch.randn(32,5)).shape

torch.Size([32, 5])

In [31]:
torch.nn.functional.relu(torch.randn(32,5)).shape

torch.Size([32, 5])

In [4]:
env = Connect4()

In [5]:
t = torch.tensor(encode_board(env)).unsqueeze(0).float()
net(t)

(tensor([0.1602, 0.1512, 0.1305, 0.1384, 0.1343, 0.1458, 0.1396],
        grad_fn=<SqueezeBackward0>),
 tensor(-0.1011, grad_fn=<SqueezeBackward0>))

In [6]:
t.shape

torch.Size([1, 6, 7, 3])

In [8]:
mcts = MCTS(net, args)

In [9]:
env.current_state

array([[' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U32')

In [10]:
torch.tensor(encode_board(env)).float().unsqueeze(0).cpu().shape

torch.Size([1, 6, 7, 3])

In [11]:
mcts.search(env)

(6, 7, 3)
[[' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ']]


0.10108617

In [14]:
mcts.Qsa

{}

In [17]:
from collections import deque

In [18]:
deque([], 5)

deque([])