In [1]:
import torch

In [2]:
import numpy as np
from game import Connect4
from arena import Arena
from players import random_play, alpha_zero_player
from network import ConnectNet
from mcts import MCTS

TypeError: __init__() missing 2 required positional arguments: 'net' and 'args'

In [ ]:
game = Connect4()


In [3]:
def human_player(board):
    valid_actions = np.where(board[0,:] == 0)[0]
    inp = int(input())
    if inp in valid_actions:
        return inp
    else:
        print("invalid action")


In [14]:
alpha_zero_player(game.init_state)

1

In [7]:
path = "networks_saved/net_init.pth"

In [19]:
args = {"exploration_constant":1.,
        "device":"cpu",
        "n_sim":50,
}

game = Connect4()
net = ConnectNet()
net.load_state_dict(torch.load(path, map_location='cpu'))
mcts = MCTS(game, net, args)



In [30]:
mcts.search(game.init_state)

-0.5499463

In [9]:
net(torch.tensor(game.init_state).float())

(tensor([[1.1577e-04, 6.6222e-02, 3.9185e-04, 9.3094e-01, 5.0333e-04, 1.8310e-03,
          2.3407e-09]], grad_fn=<ExpBackward>),
 tensor([[-0.1029]], grad_fn=<TanhBackward>))

In [15]:
def network(state):
    pi, _ = net(torch.tensor(state).float())
    return pi.argmax().item()

In [16]:
network(game.init_state)

3

In [18]:
jeu = Arena(network, human_player, game)

jeu.play_game(verbose=True)

Turn  1 Previous action  None Player  1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
None
Turn  2 Previous action  3 Player  -1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
None
3
Turn  3 Previous action  3 Player  1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]]
None
Turn  4 Previous action  3 Player  -1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]]
None
3
Turn  5 Previous action  3 Player  1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.

-1.0