In [1]:
from mcts import MCTS
import numpy as np
from tqdm import tqdm
import torch
from game import Connect4
from network import ConnectNet

In [2]:
from self_play_learning import SelfPlay

In [3]:
args = {
    "alpha":0.03,
    "epsilon":0.2,
    "cpuct":1.,
    "device":"cpu",
    "n_sim":10,
    "tauThreshold":5
}

In [4]:
game = Connect4()
net = ConnectNet()

In [5]:
sp = SelfPlay(game, net, args)

In [6]:
sp.run_episode()

[1. 1. 2. 2. 1. 1. 1.]
[2. 1. 1. 3. 1. 1. 2.]
[1. 2. 2. 1. 1. 1. 3.]
[2. 2. 1. 2. 1. 1. 1.]
[1. 1. 2. 2. 1. 1. 2.]
[2. 1. 1. 2. 1. 3. 1.]
[1. 1. 3. 2. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 5.]
[1. 1. 3. 1. 1. 1. 2.]
[ 0.  0.  0.  0.  0.  0. 10.]


[(array([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]),
  array([0.11111111, 0.11111111, 0.22222222, 0.22222222, 0.11111111,
         0.11111111, 0.11111111]),
  -1),
 (array([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.]]),
  array([0.18181818, 0.09090909, 0.09090909, 0.27272727, 0.09090909,
         0.09090909, 0.18181818]),
  1),
 (array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  1.,  0.,  0.,  0., -1.]]),
  array([0.09090909, 0.181818

In [ ]:
mcts1 = MCTS(game.init_board)